# docker-compose file
version: '3'


services:
  discovery-service:
    image: amazoncorretto:11
    volumes:
      - ./apps/discovery-service/build/libs/discovery-service.jar:/app/discovery-service.jar
    working_dir: /app
    command: java -jar discovery-service.jar
    networks:
      - lms-network
    deploy:
      replicas: 1


  user-management-service-db:
    image: postgres:${USER_MANAGEMENT_SERVICE_DB_VERSION}
    environment:
      POSTGRES_DB: ${USER_MANAGEMENT_SERVICE_DB_NAME}
      POSTGRES_USER: ${USER_MANAGEMENT_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${USER_MANAGEMENT_SERVICE_DB_PASSWORD}
    volumes:
      - user-management-service-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  user-management-service-db-data:


networks:
  lms-network:
    driver: bridge
