server:
  port: 8078

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Noman5237/LibraryManagementSystemConfig
          username: ${CLOUD_CONFIG_GITHUB_TOKEN}
          password: ${CLOUD_CONFIG_GITHUB_TOKEN}
          default-label: master

management:
  endpoints:
    web:
      exposure:
        include: "*"
