server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: auth-service
  redis:
    password: password@auth
  cloud:
    config:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /docs

security:
  jwt:
    refresh-token:
      secret: super-strong-refresh-token-secret
      expiration: 6000
    access-token:
      secret: super-strong-access-token-secret
      expiration: 12000
