server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

security:
  jwt:
    access-token:
      secret: acess
      expiration: 180
    refresh-token:
      secret: refresh
      expiration: 360
