server:
  port: 8081

# add spring data jpa source
spring:
  application:
    name: user-management-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user_management
    username: dev@user_management
    password: password@user_management
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true