server:
  port: 8079

hosts:
  user-management-service: localhost
  auth-service: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-management
          uri: http://${hosts.user-management-service}:8081
          metadata:
            docs: /api/docs
          predicates:
            - Path=/api/user-management/**
          filters:
            - RewritePath=/api/user-management/?(?<segment>.*), /api/user/$\{segment}
        - id: authentication-service
          uri: http://${hosts.auth-service}:8082
          metadata:
            public: true
            docs: /api/docs
          predicates:
            - Path=/api/authenticate/**
    config:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
