server:
  port: 8079

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-management
          metadata:
            docs: /api/docs
          uri: http://localhost:8081
          predicates:
            - Path=/api/user-management/**
          filters:
            - RewritePath=/api/user-management/?(?<segment>.*), /api/user/$\{segment}
    config:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
