server:
  port: 8079

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-management
          uri: http://localhost:8081
          predicates:
            - Path=/api/user-management/**
          filters:
            - RewritePath=/api/user-management/?(?<segment>.*), /api/user/$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: "*"
